### ISSUE TITLE
Can't retrieve credentials when using windows service

### ISSUE THREAD

**Issue by myshon** [AdysTech/CredentialManager#58]
I'm creating Worker in .NET Core 3.1 for Windows Service as described here: https://dotnetcoretutorials.com/2019/12/07/creating-windows-services-in-net-core-part-3-the-net-core-worker-way 
I'm using AdysTech.CredentialManager for API credentials in the Worker. 
            
```
var target = "MyAppName";
var cred = CredentialManager.GetCredentials(target)
```
I have generic credentials defined using Control Panel\All Control Panel Items\Credential Manager. When I run worker locally then credentials are retrieved correctly. However, when I install the worker as a service
```
sc create MyAppName ...
sc start MyAppName
```
Windows service runs correctly, but CredentialManager returns the list with a single item "XboxLive" which is the last item on the list in Credential Manager UI.  The other credentials are missing. The server runs on my local account with admin rights. 

Do you have any idea why it behaves this way?

**Comment by myshon** [comment]
I added credentials as a different user X (using runas command) and changed user of the Windows Service from the Local System to X. Then it started working.

**Comment by mvadu** [comment]
I came across this issue with my own service today. The default service create (e.g. New-Service command or sc.exe create) adds a service with SYSTEM user. Since the credentials you added are not available to that user, "other credentials are missing" is an expected behavior. One way to handle (in my case where I needed a credential to use inside my service code) is to create the credentials under SYSTEM. I used `PSExec.exe -s cmdkey.exe /add:targetname /user:username /pass:password` to add the credentials. PSExec is a sysinternal tool.
